// This file was generated by lezer-generator. You probably shouldn't edit it.
const {LRParser} = require("@lezer/lr")
exports.parser = LRParser.deserialize({
  version: 14,
  states: "!QOQOPOOOQOPO'#C`OOOO'#Cb'#CbQOOOOOO]OPO,58zOQOPO1G.fOeOPO7+$QOOOO<<Gl<<Gl",
  stateData: "j~OQQORQOVPO~OWTOXTO~OYVO~O",
  goto: "fVPPPPWP]VQOPTQROQSPRUT",
  nodeNames: "⚠ Program Name Number BinaryExpression",
  maxTerm: 10,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "!a~RVxyhyzm{|r}!Ow!Q![|!c!}!U#T#o!U~mOV~~rOY~~wOW~~|OX~~!RPR~!Q![|~!ZQQ~!c!}!U#T#o!U",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
